# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "coverlet.collector";
    version = "6.0.0";
    hash = "sha256-IEmweTMapcPhFHpmJsPXfmMhravYOrWupgjeOvMmQ4o=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Authorization";
    version = "8.0.10";
    hash = "sha256-VeUAe/OoV2zNDaiSKSv7tXR5barJzLbxS96DUb9bAz8=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Authorization";
    version = "8.0.8";
    hash = "sha256-jhb4iDyzVduz6IRPyUIilLnXEYlIGl9tf99WNEfby/A=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Components";
    version = "8.0.10";
    hash = "sha256-1yjPh10//ZGTDpUW5e9gBce/PVAfsuUa0k62hd2Zsnc=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Components";
    version = "8.0.8";
    hash = "sha256-EqVGGD1yXpKlFou3jR7QvniI1MSPV1bigZT7ZkfaBo0=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Components.Analyzers";
    version = "8.0.10";
    hash = "sha256-90cZ8Ah0t4lfZLFt/nWKaC/2t7s5PvYNiB3aed1RUqM=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Components.Analyzers";
    version = "8.0.8";
    hash = "sha256-lJ5jGfnDNB56j47XHn16jrKKiI4SR0TRB1JTxNmybJY=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Components.Forms";
    version = "8.0.10";
    hash = "sha256-juLwnJrcJquXp0AKRqU//guSZxmZ6U+Eh1EThugp/Zs=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Components.Forms";
    version = "8.0.8";
    hash = "sha256-QbDDKFnPD4TlCDAXZ5C9vsm/BPEKv6NZKkhG7xYKrQ0=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Components.Web";
    version = "8.0.10";
    hash = "sha256-0rlanGQR482n1n8fNpRGb9vqsFPbqByLsXTBeV/rKjE=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Components.Web";
    version = "8.0.8";
    hash = "sha256-EEO0FSj1HC888PSfTct1UmfapQ6XezwF2JNhlSd8aI0=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Components.WebAssembly";
    version = "8.0.10";
    hash = "sha256-m+nD2cY4FHjUqJvvOnmD3aEpJbt92fSDXrTVGjdd8hs=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Components.WebAssembly.Server";
    version = "8.0.10";
    hash = "sha256-AaSCn91XzJkN61PTBtEOjP90lubGRy7SxFtptAxEJPE=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Metadata";
    version = "8.0.10";
    hash = "sha256-SxnMOWJGgUUQyKaRezJQwMUt4eMfWjnhmfk8pldYGNA=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.Metadata";
    version = "8.0.8";
    hash = "sha256-eyxHj0o790VC4TuXDVbxjqMpKwQVRgRxDVUzBGPebZM=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.OpenApi";
    version = "8.0.5";
    hash = "sha256-H48UKpBGBxr6hgJoW9YbY1nU5eGQq0H0iC9HZ0gIVto=";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "6.0.0";
    hash = "sha256-49+H/iFwp+AfCICvWcqo9us4CzxApPKC37Q5Eqrw+JU=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeCoverage";
    version = "17.8.0";
    hash = "sha256-cv/wAXfTNS+RWEsHWNKqRDHC7LOQSSdFJ1a9cZuSfJw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.ApiDescription.Server";
    version = "6.0.5";
    hash = "sha256-RJjBWz+UHxkQE2s7CeGYdTZ218mCufrxl0eBykZdIt4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "8.0.0";
    hash = "sha256-9BPsASlxrV8ilmMCjdb3TiUcm5vFZxkBnAI/fNBSEyA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "8.0.0";
    hash = "sha256-4eBpDkf7MJozTZnOwQvwcfgRKQGcNXe0K/kF+h5Rl8o=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "8.0.2";
    hash = "sha256-aGB0VuoC34YadAEqrwoaXLc5qla55pswDV2xLSmR7SE=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.FileExtensions";
    version = "8.0.1";
    hash = "sha256-iRA8L7BX/fe5LHCVOhzBSk30GfshP7V2Qj2nxpEvStA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Json";
    version = "8.0.1";
    hash = "sha256-J8EK/yhsfTpeSUY8F81ZTBV9APHiPUliN7d+n2OX9Ig=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "8.0.0";
    hash = "sha256-+qIDR8hRzreCHNEDtUcPfVHQdurzWPo/mqviCH78+EQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "8.0.1";
    hash = "sha256-O9g0jWS+jfGoT3yqKwZYJGL+jGSIeSbwmvomKDC3hTU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.0";
    hash = "sha256-75KzEGWjbRELczJpCiJub+ltNUMMbz5A/1KQU+5dgP8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.1";
    hash = "sha256-lzTYLpRDAi3wW9uRrkTNJtMmaYdtGJJHdBLbUKu60PM=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.2";
    hash = "sha256-UfLfEQAkXxDaVPC7foE/J3FVEXd31Pu6uQIhTic3JgY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "8.0.0";
    hash = "sha256-uQSXmt47X2HGoVniavjLICbPtD2ReQOYQMgy3l0xuMU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Physical";
    version = "8.0.0";
    hash = "sha256-29y5ZRQ1ZgzVOxHktYxyiH40kVgm5un2yTGdvuSWnRc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileSystemGlobbing";
    version = "8.0.0";
    hash = "sha256-+Oz41JR5jdcJlCJOSpQIL5OMBNi+1Hl2d0JUHfES7sU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Localization";
    version = "8.0.8";
    hash = "sha256-dX8HUYxWuzQUJfMW3WyH6mPFlh5i+J9UdND1rhkjwMs=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Localization.Abstractions";
    version = "8.0.8";
    hash = "sha256-DfzIHT+S86FYQDtTKxrdwpiEgUFp+zQlIdlMytNksnQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "8.0.1";
    hash = "sha256-vkfVw4tQEg86Xg18v6QO0Qb4Ysz0Njx57d1XcNuj6IU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "8.0.1";
    hash = "sha256-TYce3qvMr92JbAZ62ATBsocaH0joJzw0px0tYGZ9N0U=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "8.0.2";
    hash = "sha256-cHpe8X2BgYa5DzulZfq24rg8O2K5Lmq2OiLhoyAVgJc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "8.0.2";
    hash = "sha256-AjcldddddtN/9aH9pg7ClEZycWtFHLi9IPe1GGhNQys=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "8.0.0";
    hash = "sha256-FU8qj3DR8bDdc1c+WeGZx/PCZeqqndweZM9epcpXjSo=";
  })
  (fetchNuGet {
    pname = "Microsoft.JSInterop";
    version = "8.0.10";
    hash = "sha256-XFdPuNG0rSILCdGk6XTAYWaVcvYravrDGDOsOv3CpDg=";
  })
  (fetchNuGet {
    pname = "Microsoft.JSInterop";
    version = "8.0.8";
    hash = "sha256-Mexoz07Bb3SRp1Gjfuvb25ZgPUnpmOq3wjZZhnBP0X0=";
  })
  (fetchNuGet {
    pname = "Microsoft.JSInterop.WebAssembly";
    version = "8.0.10";
    hash = "sha256-yUsBvNj06bFwAqQ7kTP7EX/S+BDBqLB3+OU97+EXJ0E=";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Sdk.WebAssembly.Pack";
    version = "8.0.5";
    hash = "sha256-d2r7Tx/z1R7q2qQKWY4pKIljrA4RHAQGBbt1wY2h//s=";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Test.Sdk";
    version = "17.8.0";
    hash = "sha256-uz7QvW+NsVRsp8FR1wjnGEOkUaPX4JyieywvCN6g2+s=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.Mono.browser-wasm";
    version = "8.0.5";
    hash = "sha256-srTajLH7HTg7Dqq01bdKlnVfMdTO3kQT/Oop/WGtTe0=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    hash = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl9ObJ0IOcCM=";
  })
  (fetchNuGet {
    pname = "Microsoft.OpenApi";
    version = "1.2.3";
    hash = "sha256-OafkxXKnDmLZo5tjifjycax0n0F/OnWQTEZCntBMYR0=";
  })
  (fetchNuGet {
    pname = "Microsoft.OpenApi";
    version = "1.4.3";
    hash = "sha256-vk47e78OwopXJx2LhDRbKFObqF3GShHfNHR2SzvbQeA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Playwright";
    version = "1.27.1";
    hash = "sha256-9GuXfDkv+MsDBCQaVsqJvNfS5CeDm3kLVL1QDpbiam8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Playwright.NUnit";
    version = "1.27.1";
    hash = "sha256-tiqRJuN8IBgHmNf5chcrbqnhQc5M8XBqXXrM+p1pFww=";
  })
  (fetchNuGet {
    pname = "Microsoft.Playwright.TestAdapter";
    version = "1.27.1";
    hash = "sha256-Hwx7Ry/4EayjE3a+FSG/3YWXQ+OJgrq+e1tYCl57XRw=";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "17.3.0";
    hash = "sha256-+1UPtpq/zT0AqzS8Wnmw9+ahS6yRQVvqutQxFnpNn2A=";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "17.8.0";
    hash = "sha256-9TwGrjVvbtyetw67Udp3EMK5MX8j0RFRjduxPCs9ESw=";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.TestHost";
    version = "17.8.0";
    hash = "sha256-+CTYFu631uovLCO47RKe86YaAqfoLA4r73vKORJUsjg=";
  })
  (fetchNuGet {
    pname = "MudBlazor";
    version = "7.12.1";
    hash = "sha256-jaSYsm2mZYx6FO+LqN+tyCx/NVGimLXbliYf4VzmkXY=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "2.0.0";
    hash = "sha256-Pp7fRylai8JrE1O+9TGfIEJrAOmnWTJRLWE+qJBahK0=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    hash = "sha256-K2tSVW4n4beRPzPu3rlVaBEMdGvWSv/3Q1fxaDh4Mjo=";
  })
  (fetchNuGet {
    pname = "NuGet.Frameworks";
    version = "5.11.0";
    hash = "sha256-n+hxcrf+sXM80Tv9YH9x4+hwTslVidFq4tjBNPAzYnM=";
  })
  (fetchNuGet {
    pname = "NuGet.Frameworks";
    version = "6.5.0";
    hash = "sha256-ElqfN4CcKxT3hP2qvxxObb4mnBlYG89IMxO0Sm5oZ2g=";
  })
  (fetchNuGet {
    pname = "NUnit";
    version = "3.14.0";
    hash = "sha256-CuP/q5HovPWfAW3Cty/QxRi7VpjykJ3TDLq5TENI6KY=";
  })
  (fetchNuGet {
    pname = "NUnit.Analyzers";
    version = "3.9.0";
    hash = "sha256-+CmhyW6kJOnevFUAwnMH5sPv1KGc/l1y/R2wAN0Ec40=";
  })
  (fetchNuGet {
    pname = "NUnit3TestAdapter";
    version = "4.5.0";
    hash = "sha256-ER3ogl0L5FYyc6pVVPY1ch+AQxG/WgFcnWECnYQJPes=";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore";
    version = "6.4.0";
    hash = "sha256-czuCv3Os7Oo06m3W+auJjrTGuYT82E+Bi80sJqeVb8o=";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore.Swagger";
    version = "6.4.0";
    hash = "sha256-1u4A9vzDUJ+wLoxH5yQEVhpOxi+VnAMd64Z18SLqjPE=";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore.SwaggerGen";
    version = "6.4.0";
    hash = "sha256-Alra5J+i0L/4JoS5pATJexVu8LId8HZcofkx7KiRqMw=";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore.SwaggerUI";
    version = "6.4.0";
    hash = "sha256-P84wlE4EVruLVGGTUHK29wWYs/BTq/MR5P7PuSBwr+c=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Annotations";
    version = "5.0.0";
    hash = "sha256-0pST1UHgpeE6xJrYf5R+U7AwIlH3rVC3SpguilI/MAg=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "8.0.0";
    hash = "sha256-LdpB1s4vQzsOODaxiKstLks57X9DTD5D6cPx8DE1wwE=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.6.0";
    hash = "sha256-JJfgaPav7UfEh4yRAQdGhLZF1brr0tUWPl6qmfNWq/E=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    hash = "sha256-bEG1PnDp7uKYz/OgLOWs3RWwQSVYm+AnPwVmAmcgp2I=";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "6.0.0";
    hash = "sha256-UemDHGFoQIG7ObQwRluhVf6AgtQikfHEoPLC6gbFyRo=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "6.0.5";
    hash = "sha256-NKWNrCcKy8S5ldsJzm6+udU53fWzmPGZZG/gpk0Kz4k=";
  })
]
