// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoeNix.Persistence;

#nullable disable

namespace PhoeNix.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250602191619_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.ConfigurationHome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("HomeId");

                    b.ToTable("ConfigurationHomes");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.ConfigurationInput", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InputId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("InputId");

                    b.ToTable("ConfigurationInput");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.ConfigurationModule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("ModuleId");

                    b.ToTable("ConfigurationModules");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.ConfigurationSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("SystemId");

                    b.ToTable("ConfigurationSystems");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Homes.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Homes.HomeModule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("ModuleId");

                    b.ToTable("HomeModules");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Homes.HomeUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HomeId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("HomeId1")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("HomeUsers");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FollowsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FollowsId");

                    b.ToTable("Inputs");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.EntryValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT")
                        .HasColumnName("TypeDiscriminator");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("EntryValues");

                    b.HasDiscriminator<string>("TypeDiscriminator").HasValue("EntryValue");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.System", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Architecture")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.SystemModule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SystemId");

                    b.ToTable("SystemModules");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNormalUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Shell")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Uid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.MultiChoiceValue<double>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("MultiChoiceDouble");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.MultiChoiceValue<int>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("MultiChoiceInt");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.MultiChoiceValue<string>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("MultiChoiceString");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.RangeValue<double>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.Property<double>("LowerValue")
                        .HasColumnType("REAL");

                    b.Property<double>("Max")
                        .HasColumnType("REAL");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.Property<double>("UpperValue")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("RangeDouble");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.RangeValue<int>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.Property<int>("LowerValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpperValue")
                        .HasColumnType("INTEGER");

                    b.ToTable("EntryValues", t =>
                        {
                            t.Property("LowerValue")
                                .HasColumnName("RangeValue_LowerValue");

                            t.Property("Max")
                                .HasColumnName("RangeValue_Max");

                            t.Property("Min")
                                .HasColumnName("RangeValue_Min");

                            t.Property("UpperValue")
                                .HasColumnName("RangeValue_UpperValue");
                        });

                    b.HasDiscriminator().HasValue("RangeInt");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.TextValue", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.ConfigurationHome", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", "Configuration")
                        .WithMany("Homes")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoeNix.Domain.Entities.Homes.Home", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.ConfigurationInput", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", "Configuration")
                        .WithMany("Inputs")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoeNix.Domain.Entities.Inputs.Input", "Input")
                        .WithMany()
                        .HasForeignKey("InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Input");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.ConfigurationModule", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", "Configuration")
                        .WithMany("Modules")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoeNix.Domain.Entities.Modules.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.ConfigurationSystem", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", "Configuration")
                        .WithMany("Systems")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoeNix.Domain.Entities.Systems.System", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("System");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Homes.HomeModule", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Homes.Home", "Home")
                        .WithMany("Modules")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoeNix.Domain.Entities.Modules.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Homes.HomeUser", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Homes.Home", "Home")
                        .WithMany("Users")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoeNix.Domain.Entities.Homes.Home", null)
                        .WithOne("HomeUser")
                        .HasForeignKey("PhoeNix.Domain.Entities.Homes.HomeUser", "HomeId1");

                    b.HasOne("PhoeNix.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Inputs.Input", "Follows")
                        .WithMany("Followers")
                        .HasForeignKey("FollowsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Follows");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.EntryValue", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Modules.Module", null)
                        .WithMany("EditableValues")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.SystemModule", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Modules.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhoeNix.Domain.Entities.Systems.System", "System")
                        .WithMany("Modules")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("System");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.Configuration", b =>
                {
                    b.Navigation("Homes");

                    b.Navigation("Inputs");

                    b.Navigation("Modules");

                    b.Navigation("Systems");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Homes.Home", b =>
                {
                    b.Navigation("HomeUser")
                        .IsRequired();

                    b.Navigation("Modules");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.Navigation("Followers");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.Module", b =>
                {
                    b.Navigation("EditableValues");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.System", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
