// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PhoeNix.Persistence;

#nullable disable

namespace PhoeNix.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260716152918_AddBootstrapUseSubstituters")]
    partial class AddBootstrapUseSubstituters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhoeNix.Application.Models.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "NextAttemptOnUtc", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.AppSettings.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BootstrapUseSubstituters")
                        .HasColumnType("boolean");

                    b.Property<double>("DeployCaCertificateTtlDays")
                        .HasColumnType("double precision");

                    b.Property<string>("DeployCaDeployUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DeployCaKeyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DeployCaKeyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeployCaPrincipal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FileStorageRootPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HardwareProbeBootstrapUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("HardwareProbeConnectTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("HardwareProbeDisableHostKeyChecking")
                        .HasColumnType("boolean");

                    b.Property<string>("HardwareProbeProbeCommand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("HardwareProbeProbeTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("HardwareProbeSshExecutable")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("InstallerBuildOnTarget")
                        .HasColumnType("boolean");

                    b.Property<bool>("InstallerCopyHostKeys")
                        .HasColumnType("boolean");

                    b.Property<bool>("InstallerDisableHostKeyChecking")
                        .HasColumnType("boolean");

                    b.Property<string>("InstallerExecutableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InstallerTargetUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("InstallerTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("LocalDomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MonitoringAddressResolution")
                        .HasColumnType("integer");

                    b.Property<string>("MonitoringPrometheusEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("MonitoringTokenTtlDays")
                        .HasColumnType("double precision");

                    b.Property<string>("NetbootApiBasePublicUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NetbootHostExecutablePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NetbootListenAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NetbootPort")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<double>("SshCaCertificateTtlHours")
                        .HasColumnType("double precision");

                    b.Property<string>("SshCaKeyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SshCaKeyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SshCaPrincipal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubstituterKeys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Substituters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdaterBuildHost")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("UpdaterFast")
                        .HasColumnType("boolean");

                    b.Property<bool>("UpdaterUseRemoteSudo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Configurations", (string)null);
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.FollowInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FollowName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FollowValue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("InputId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InputId");

                    b.ToTable("FollowInput");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("Inputs");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Machines.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("InstallDiskSelectionPreference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.EntryValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EntryValueKind")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<Guid>("ModuleValueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModuleValueId");

                    b.ToTable("EntryValues", (string)null);

                    b.HasDiscriminator<string>("EntryValueKind").HasValue("EntryValue");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("SupportedArchitectures")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Name", "OwnerId")
                        .IsUnique();

                    b.ToTable("ModuleTemplates", (string)null);
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SystemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("ModuleTemplateId");

                    b.HasIndex("SystemId");

                    b.ToTable("ModuleValue");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModuleTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<string[]>("VariableNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ModuleTemplateId");

                    b.HasIndex("ModuleTemplateId", "Name")
                        .IsUnique();

                    b.ToTable("ModuleTemplateTests", (string)null);
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.SetupSessions.SetupSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BootstrapBuildError")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("SetupSessions");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.System", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Architecture")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.DecimalRangeValue", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.Property<decimal?>("LowerValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Max")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Min")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UpperValue")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue("DecimalRange");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.IntegerRangeValue", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.Property<int?>("LowerValue")
                        .HasColumnType("integer");

                    b.Property<int>("Max")
                        .HasColumnType("integer");

                    b.Property<int>("Min")
                        .HasColumnType("integer");

                    b.Property<int>("UpperValue")
                        .HasColumnType("integer");

                    b.ToTable("EntryValues", t =>
                        {
                            t.Property("LowerValue")
                                .HasColumnName("IntegerRangeValue_LowerValue");

                            t.Property("Max")
                                .HasColumnName("IntegerRangeValue_Max");

                            t.Property("Min")
                                .HasColumnName("IntegerRangeValue_Min");

                            t.Property("UpperValue")
                                .HasColumnName("IntegerRangeValue_UpperValue");
                        });

                    b.HasDiscriminator().HasValue("IntegerRange");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ListValue", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("List");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.SingleChoiceValue", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.PrimitiveCollection<string[]>("Options")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue("SingleChoice");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.TextValue", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.AppSettings.AppSettings", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.Configuration", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.FollowInput", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Inputs.Input", null)
                        .WithMany("Followers")
                        .HasForeignKey("InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", null)
                        .WithMany("Inputs")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Machines.Machine", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PhoeNix.Domain.Entities.Machines.DeploymentSnapshot", "DeploymentSnapshot", b1 =>
                        {
                            b1.Property<Guid>("MachineId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ConfigurationId")
                                .HasColumnType("uuid")
                                .HasColumnName("ProvisionedConfigurationId");

                            b1.Property<string>("ConfigurationTitle")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ConfigurationTitle");

                            b1.Property<string>("LastKnownIpAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ProvisionedIpAddress");

                            b1.Property<DateTime>("ProvisionedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ProvisionedAtUtc");

                            b1.Property<Guid>("SystemId")
                                .HasColumnType("uuid")
                                .HasColumnName("ProvisionedSystemId");

                            b1.Property<string>("SystemName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("SystemName");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");

                            b1.OwnsMany("PhoeNix.Domain.Entities.Machines.DeploymentDiskBinding", "BoundDisks", b2 =>
                                {
                                    b2.Property<Guid>("MachineId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Index")
                                        .HasColumnType("integer")
                                        .HasColumnName("DiskIndex");

                                    b2.Property<string>("StableDevicePath")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("StableDevicePath");

                                    b2.HasKey("MachineId", "Index");

                                    b2.HasIndex("StableDevicePath");

                                    b2.ToTable("MachineDeploymentBoundDisks", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MachineId");
                                });

                            b1.Navigation("BoundDisks");
                        });

                    b.OwnsOne("PhoeNix.Domain.Entities.Machines.HardwareProfile", "HardwareProfile", b1 =>
                        {
                            b1.Property<Guid>("MachineId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ObservedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("HardwareObservedAtUtc");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");

                            b1.OwnsOne("PhoeNix.Domain.Entities.Machines.CpuProfile", "Cpu", b2 =>
                                {
                                    b2.Property<Guid>("HardwareProfileMachineId")
                                        .HasColumnType("uuid");

                                    b2.Property<int?>("CoreCount")
                                        .HasColumnType("integer")
                                        .HasColumnName("CpuCoreCount");

                                    b2.Property<string>("Model")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("CpuModel");

                                    b2.Property<int?>("ThreadCount")
                                        .HasColumnType("integer")
                                        .HasColumnName("CpuThreadCount");

                                    b2.Property<string>("Vendor")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("CpuVendor");

                                    b2.HasKey("HardwareProfileMachineId");

                                    b2.ToTable("Machines");

                                    b2.WithOwner()
                                        .HasForeignKey("HardwareProfileMachineId");
                                });

                            b1.OwnsOne("PhoeNix.Domain.Entities.Machines.MemoryProfile", "Memory", b2 =>
                                {
                                    b2.Property<Guid>("HardwareProfileMachineId")
                                        .HasColumnType("uuid");

                                    b2.Property<int?>("OccupiedSlotCount")
                                        .HasColumnType("integer")
                                        .HasColumnName("MemoryOccupiedSlotCount");

                                    b2.Property<int?>("SlotCount")
                                        .HasColumnType("integer")
                                        .HasColumnName("MemorySlotCount");

                                    b2.Property<long?>("TotalBytes")
                                        .HasColumnType("bigint")
                                        .HasColumnName("MemoryTotalBytes");

                                    b2.HasKey("HardwareProfileMachineId");

                                    b2.ToTable("Machines");

                                    b2.WithOwner()
                                        .HasForeignKey("HardwareProfileMachineId");

                                    b2.OwnsMany("PhoeNix.Domain.Entities.Machines.MemoryModuleProfile", "Modules", b3 =>
                                        {
                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<int>("Id"));

                                            b3.Property<Guid?>("MachineId")
                                                .HasColumnType("uuid");

                                            b3.Property<long?>("SizeBytes")
                                                .HasColumnType("bigint");

                                            b3.Property<string>("Slot")
                                                .HasMaxLength(100)
                                                .HasColumnType("character varying(100)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("MachineId");

                                            b3.ToTable("MachineMemoryModules", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("MachineId");
                                        });

                                    b2.Navigation("Modules");
                                });

                            b1.OwnsOne("PhoeNix.Domain.Entities.Machines.MotherboardProfile", "Motherboard", b2 =>
                                {
                                    b2.Property<Guid>("HardwareProfileMachineId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Model")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("MotherboardModel");

                                    b2.Property<string>("Vendor")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("MotherboardVendor");

                                    b2.HasKey("HardwareProfileMachineId");

                                    b2.ToTable("Machines");

                                    b2.WithOwner()
                                        .HasForeignKey("HardwareProfileMachineId");
                                });

                            b1.OwnsMany("PhoeNix.Domain.Entities.Machines.DiskProfile", "Disks", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("BusType")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)");

                                    b2.Property<bool?>("IsRotational")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("KernelDevicePath")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.Property<Guid?>("MachineId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Model")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)");

                                    b2.Property<long?>("SizeBytes")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("StableDevicePath")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)");

                                    b2.Property<string>("Vendor")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MachineId");

                                    b2.ToTable("MachineDisks", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MachineId");
                                });

                            b1.OwnsMany("PhoeNix.Domain.Entities.Machines.GpuProfile", "Gpus", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid?>("MachineId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Model")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)");

                                    b2.Property<string>("Vendor")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)");

                                    b2.Property<long?>("VramBytes")
                                        .HasColumnType("bigint");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MachineId");

                                    b2.ToTable("MachineGpus", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MachineId");
                                });

                            b1.OwnsMany("PhoeNix.Domain.Entities.Machines.PeripheralProfile", "Peripherals", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<bool>("IsConnected")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Kind")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)");

                                    b2.Property<Guid?>("MachineId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Name")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MachineId");

                                    b2.ToTable("MachinePeripherals", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MachineId");
                                });

                            b1.Navigation("Cpu");

                            b1.Navigation("Disks");

                            b1.Navigation("Gpus");

                            b1.Navigation("Memory");

                            b1.Navigation("Motherboard");

                            b1.Navigation("Peripherals");
                        });

                    b.OwnsOne("PhoeNix.Domain.Entities.Machines.MachineStatus", "MachineStatus", b1 =>
                        {
                            b1.Property<Guid>("MachineId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime?>("LastConfigured")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastConfigured");

                            b1.Property<DateTime?>("LastContacted")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastContacted");

                            b1.Property<DateTime?>("LastOrchestrated")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastOrchestrated");

                            b1.Property<DateTime?>("LastProvisioned")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastProvisioned");

                            b1.Property<string>("MachineState")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("MachineState");

                            b1.HasKey("MachineId");

                            b1.HasIndex("MachineState");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.OwnsOne("PhoeNix.Domain.Entities.Machines.SoftwareSnapshot", "SoftwareSnapshot", b1 =>
                        {
                            b1.Property<Guid>("MachineId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("SchemaVersion")
                                .HasColumnType("integer");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.Navigation("DeploymentSnapshot");

                    b.Navigation("HardwareProfile");

                    b.Navigation("MachineStatus")
                        .IsRequired();

                    b.Navigation("SoftwareSnapshot");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.EntryValue", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Modules.ModuleValue", null)
                        .WithMany("EditableValues")
                        .HasForeignKey("ModuleValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleTemplate", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("PhoeNix.Domain.Entities.Modules.EntryValueDefinition", "EditableValueTypes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowLowerValue")
                                .HasColumnType("boolean");

                            b1.Property<int?>("BindingIndex")
                                .HasColumnType("integer");

                            b1.Property<string>("BindingKind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal?>("DecimalMax")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("DecimalMin")
                                .HasColumnType("numeric");

                            b1.Property<string>("DefaultLowerValue")
                                .HasColumnType("text");

                            b1.Property<string>("DefaultValue")
                                .HasColumnType("text");

                            b1.Property<int?>("IntegerMax")
                                .HasColumnType("integer");

                            b1.Property<int?>("IntegerMin")
                                .HasColumnType("integer");

                            b1.Property<Guid>("ModuleTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("OptionsJson")
                                .HasColumnType("text");

                            b1.Property<string>("Placeholder")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("ValueKind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("ModuleTemplateId");

                            b1.HasIndex("ModuleTemplateId", "Name")
                                .IsUnique();

                            b1.HasIndex("ModuleTemplateId", "Placeholder")
                                .IsUnique();

                            b1.ToTable("ModuleTemplateEntryValueDefinitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ModuleTemplateId");
                        });

                    b.OwnsMany("PhoeNix.Domain.Entities.Modules.RequiredInputDefinition", "RequiredInputs", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ModuleTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("ModuleTemplateId");

                            b1.ToTable("ModuleTemplateRequiredInputs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ModuleTemplateId");
                        });

                    b.Navigation("EditableValueTypes");

                    b.Navigation("RequiredInputs");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleValue", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", null)
                        .WithMany("Modules")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhoeNix.Domain.Entities.Systems.System", null)
                        .WithMany("Modules")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.Test", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Modules.ModuleTemplate", null)
                        .WithMany("Tests")
                        .HasForeignKey("ModuleTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.SetupSessions.SetupSession", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PhoeNix.Domain.Entities.SetupSessions.BootstrapImageDescriptor", "BootArtefactDescriptor", b1 =>
                        {
                            b1.Property<Guid>("SetupSessionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Init")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CmdLine");

                            b1.Property<string>("Kernel")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("KernelLocation");

                            b1.Property<string>("RamDisk")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("InitRdLocation");

                            b1.HasKey("SetupSessionId");

                            b1.ToTable("SetupSessions");

                            b1.WithOwner()
                                .HasForeignKey("SetupSessionId");
                        });

                    b.OwnsMany("PhoeNix.Domain.Entities.SetupSessions.SetupTarget", "Targets", b1 =>
                        {
                            b1.Property<Guid>("SetupSessionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MachineId")
                                .HasColumnType("uuid")
                                .HasColumnName("MachineId");

                            b1.Property<string>("IpAddress")
                                .HasColumnType("text")
                                .HasColumnName("IpAddress");

                            b1.Property<DateTime?>("LastErrorAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastErrorAtUtc");

                            b1.Property<string>("LastErrorCode")
                                .HasColumnType("text")
                                .HasColumnName("LastErrorCode");

                            b1.Property<string>("LastErrorDescription")
                                .HasColumnType("text")
                                .HasColumnName("LastErrorDescription");

                            b1.Property<string>("LastErrorSource")
                                .HasColumnType("text")
                                .HasColumnName("LastErrorSource");

                            b1.Property<DateTime?>("LastTransitionAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("LastTransitionAtUtc");

                            b1.Property<Guid?>("SelectedConfigurationId")
                                .HasColumnType("uuid")
                                .HasColumnName("SelectedConfigurationId");

                            b1.Property<Guid?>("SelectedSystemId")
                                .HasColumnType("uuid")
                                .HasColumnName("SelectedSystemId");

                            b1.Property<string>("Stage")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SetupSessionId", "MachineId");

                            b1.HasIndex("MachineId");

                            b1.HasIndex("SelectedConfigurationId");

                            b1.HasIndex("SelectedSystemId");

                            b1.ToTable("SetupSessionTargets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SetupSessionId");

                            b1.OwnsMany("PhoeNix.Domain.Entities.SetupSessions.RankedDiskAssignment", "RankedDiskAssignments", b2 =>
                                {
                                    b2.Property<Guid>("SetupSessionId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("MachineId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Index")
                                        .HasColumnType("integer")
                                        .HasColumnName("RankIndex");

                                    b2.Property<string>("DiskByIdPath")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("DiskByIdPath");

                                    b2.HasKey("SetupSessionId", "MachineId", "Index");

                                    b2.HasIndex("DiskByIdPath");

                                    b2.ToTable("SetupSessionTargetRankedDisks", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SetupSessionId", "MachineId");
                                });

                            b1.OwnsOne("PhoeNix.Domain.Entities.SetupSessions.CallbackToken", "CallbackToken", b2 =>
                                {
                                    b2.Property<Guid>("SetupTargetSetupSessionId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("SetupTargetMachineId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("ExpiresAtUtc")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("CallbackTokenExpiresAtUtc");

                                    b2.Property<DateTime?>("RevokedAtUtc")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("CallbackTokenRevokedAtUtc");

                                    b2.Property<string>("Token")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CallbackToken");

                                    b2.HasKey("SetupTargetSetupSessionId", "SetupTargetMachineId");

                                    b2.ToTable("SetupSessionTargets");

                                    b2.WithOwner()
                                        .HasForeignKey("SetupTargetSetupSessionId", "SetupTargetMachineId");
                                });

                            b1.Navigation("CallbackToken");

                            b1.Navigation("RankedDiskAssignments");
                        });

                    b.OwnsOne("PhoeNix.Domain.Entities.SetupSessions.SshCredential", "SshCredential", b1 =>
                        {
                            b1.Property<Guid>("SetupSessionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CertificatePublicKey")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SshCertificatePublicKey");

                            b1.Property<DateTime>("ExpiresAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("SshKeyExpiresAtUtc");

                            b1.Property<string>("PublicKey")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SshPublicKey");

                            b1.Property<DateTime?>("RevokedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("SshKeyRevokedAtUtc");

                            b1.HasKey("SetupSessionId");

                            b1.ToTable("SetupSessions");

                            b1.WithOwner()
                                .HasForeignKey("SetupSessionId");
                        });

                    b.Navigation("BootArtefactDescriptor");

                    b.Navigation("SshCredential");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.System", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", null)
                        .WithMany("SystemSpecifications")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.Configuration", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Modules");

                    b.Navigation("SystemSpecifications");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.Navigation("Followers");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleTemplate", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleValue", b =>
                {
                    b.Navigation("EditableValues");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.System", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
