// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoeNix.Persistence;

#nullable disable

namespace PhoeNix.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327210349_UpdateMachineDeploymentSnapshot")]
    partial class UpdateMachineDeploymentSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PhoeNix.Application.Models.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc", "NextAttemptOnUtc", "OccurredOnUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.FollowInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowValue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InputId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InputId");

                    b.ToTable("FollowInput");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("Inputs");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Machines.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallDiskSelectionPreference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.EntryValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleValueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT")
                        .HasColumnName("TypeDiscriminator");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleValueId");

                    b.ToTable("EntryValues");

                    b.HasDiscriminator<string>("TypeDiscriminator").HasValue("EntryValue");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("_supportedArchitectures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModuleTemplates");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModuleTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SystemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("ModuleTemplateId");

                    b.HasIndex("SystemId");

                    b.ToTable("ModuleValue");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("_variableNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleTemplateId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.SetupSessions.SetupSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SetupSessions");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.SystemUsers.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNormalUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Shell")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Uid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.System", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Architecture")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.MultiChoiceValue<double>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("MultiChoiceDouble");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.MultiChoiceValue<int>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("MultiChoiceInt");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.MultiChoiceValue<string>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("MultiChoiceString");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.RangeValue<double>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.Property<double>("LowerValue")
                        .HasColumnType("REAL");

                    b.Property<double>("Max")
                        .HasColumnType("REAL");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.Property<double>("UpperValue")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("RangeDouble");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.RangeValue<int>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.Property<int>("LowerValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpperValue")
                        .HasColumnType("INTEGER");

                    b.ToTable("EntryValues", t =>
                        {
                            t.Property("LowerValue")
                                .HasColumnName("RangeValue_LowerValue");

                            t.Property("Max")
                                .HasColumnName("RangeValue_Max");

                            t.Property("Min")
                                .HasColumnName("RangeValue_Min");

                            t.Property("UpperValue")
                                .HasColumnName("RangeValue_UpperValue");
                        });

                    b.HasDiscriminator().HasValue("RangeInt");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.TextValue", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.FollowInput", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Inputs.Input", null)
                        .WithMany("Followers")
                        .HasForeignKey("InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", null)
                        .WithMany("Inputs")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Machines.Machine", b =>
                {
                    b.OwnsOne("PhoeNix.Domain.Entities.Machines.DeploymentSnapshot", "DeploymentSnapshot", b1 =>
                        {
                            b1.Property<Guid>("MachineId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ConfigurationId")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvisionedConfigurationId");

                            b1.Property<string>("LastKnownIpAddress")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvisionedIpAddress");

                            b1.Property<DateTime>("ProvisionedAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvisionedAtUtc");

                            b1.Property<Guid>("SystemId")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvisionedSystemId");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");

                            b1.OwnsMany("PhoeNix.Domain.Entities.Machines.DeploymentDiskBinding", "BoundDisks", b2 =>
                                {
                                    b2.Property<Guid>("MachineId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Index")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("DiskIndex");

                                    b2.Property<string>("StableDevicePath")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("StableDevicePath");

                                    b2.HasKey("MachineId", "Index");

                                    b2.HasIndex("StableDevicePath");

                                    b2.ToTable("MachineDeploymentBoundDisks", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MachineId");
                                });

                            b1.Navigation("BoundDisks");
                        });

                    b.OwnsOne("PhoeNix.Domain.Entities.Machines.HardwareProfile", "HardwareProfile", b1 =>
                        {
                            b1.Property<Guid>("MachineId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("ObservedAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("HardwareObservedAtUtc");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");

                            b1.OwnsOne("PhoeNix.Domain.Entities.Machines.CpuProfile", "Cpu", b2 =>
                                {
                                    b2.Property<Guid>("HardwareProfileMachineId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int?>("CoreCount")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("CpuCoreCount");

                                    b2.Property<string>("Model")
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CpuModel");

                                    b2.Property<int?>("ThreadCount")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("CpuThreadCount");

                                    b2.Property<string>("Vendor")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CpuVendor");

                                    b2.HasKey("HardwareProfileMachineId");

                                    b2.ToTable("Machines");

                                    b2.WithOwner()
                                        .HasForeignKey("HardwareProfileMachineId");
                                });

                            b1.OwnsOne("PhoeNix.Domain.Entities.Machines.MemoryProfile", "Memory", b2 =>
                                {
                                    b2.Property<Guid>("HardwareProfileMachineId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int?>("OccupiedSlotCount")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("MemoryOccupiedSlotCount");

                                    b2.Property<int?>("SlotCount")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("MemorySlotCount");

                                    b2.Property<long?>("TotalBytes")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("MemoryTotalBytes");

                                    b2.HasKey("HardwareProfileMachineId");

                                    b2.ToTable("Machines");

                                    b2.WithOwner()
                                        .HasForeignKey("HardwareProfileMachineId");

                                    b2.OwnsMany("PhoeNix.Domain.Entities.Machines.MemoryModuleProfile", "Modules", b3 =>
                                        {
                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("INTEGER");

                                            b3.Property<Guid?>("MachineId")
                                                .HasColumnType("TEXT");

                                            b3.Property<long?>("SizeBytes")
                                                .HasColumnType("INTEGER");

                                            b3.Property<string>("Slot")
                                                .HasMaxLength(100)
                                                .HasColumnType("TEXT");

                                            b3.HasKey("Id");

                                            b3.HasIndex("MachineId");

                                            b3.ToTable("MachineMemoryModules", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("MachineId");
                                        });

                                    b2.Navigation("Modules");
                                });

                            b1.OwnsOne("PhoeNix.Domain.Entities.Machines.MotherboardProfile", "Motherboard", b2 =>
                                {
                                    b2.Property<Guid>("HardwareProfileMachineId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Model")
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("MotherboardModel");

                                    b2.Property<string>("Vendor")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("MotherboardVendor");

                                    b2.HasKey("HardwareProfileMachineId");

                                    b2.ToTable("Machines");

                                    b2.WithOwner()
                                        .HasForeignKey("HardwareProfileMachineId");
                                });

                            b1.OwnsMany("PhoeNix.Domain.Entities.Machines.DiskProfile", "Disks", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("BusType")
                                        .HasMaxLength(100)
                                        .HasColumnType("TEXT");

                                    b2.Property<bool?>("IsRotational")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("KernelDevicePath")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid?>("MachineId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Model")
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.Property<long?>("SizeBytes")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("StableDevicePath")
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Vendor")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MachineId");

                                    b2.ToTable("MachineDisks", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MachineId");
                                });

                            b1.OwnsMany("PhoeNix.Domain.Entities.Machines.GpuProfile", "Gpus", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid?>("MachineId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Model")
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Vendor")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.Property<long?>("VramBytes")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MachineId");

                                    b2.ToTable("MachineGpus", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MachineId");
                                });

                            b1.OwnsMany("PhoeNix.Domain.Entities.Machines.PeripheralProfile", "Peripherals", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<bool>("IsConnected")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Kind")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid?>("MachineId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .HasMaxLength(300)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MachineId");

                                    b2.ToTable("MachinePeripherals", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MachineId");
                                });

                            b1.Navigation("Cpu");

                            b1.Navigation("Disks");

                            b1.Navigation("Gpus");

                            b1.Navigation("Memory");

                            b1.Navigation("Motherboard");

                            b1.Navigation("Peripherals");
                        });

                    b.OwnsOne("PhoeNix.Domain.Entities.Machines.MachineStatus", "MachineStatus", b1 =>
                        {
                            b1.Property<Guid>("MachineId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("LastConfigured")
                                .HasColumnType("TEXT")
                                .HasColumnName("LastConfigured");

                            b1.Property<DateTime?>("LastContacted")
                                .HasColumnType("TEXT")
                                .HasColumnName("LastContacted");

                            b1.Property<DateTime?>("LastOrchestrated")
                                .HasColumnType("TEXT")
                                .HasColumnName("LastOrchestrated");

                            b1.Property<DateTime?>("LastProvisioned")
                                .HasColumnType("TEXT")
                                .HasColumnName("LastProvisioned");

                            b1.Property<string>("MachineState")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("MachineState");

                            b1.HasKey("MachineId");

                            b1.HasIndex("MachineState");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.OwnsOne("PhoeNix.Domain.Entities.Machines.SoftwareSnapshot", "SoftwareSnapshot", b1 =>
                        {
                            b1.Property<Guid>("MachineId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("SchemaVersion")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.Navigation("DeploymentSnapshot");

                    b.Navigation("HardwareProfile");

                    b.Navigation("MachineStatus")
                        .IsRequired();

                    b.Navigation("SoftwareSnapshot");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.EntryValue", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Modules.ModuleValue", null)
                        .WithMany("EditableValues")
                        .HasForeignKey("ModuleValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleTemplate", b =>
                {
                    b.OwnsMany("PhoeNix.Domain.Entities.Modules.EntryValueDefinition", "EditableValueTypes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("BindingIndex")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BindingKind")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("InputType")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ModuleTemplateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Placeholder")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ModuleTemplateId");

                            b1.ToTable("ModuleTemplateEntryValueDefinitions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ModuleTemplateId");
                        });

                    b.Navigation("EditableValueTypes");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleValue", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", null)
                        .WithMany("Modules")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhoeNix.Domain.Entities.Systems.System", null)
                        .WithMany("Modules")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.Test", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Modules.ModuleTemplate", null)
                        .WithMany("Tests")
                        .HasForeignKey("ModuleTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.SetupSessions.SetupSession", b =>
                {
                    b.OwnsOne("PhoeNix.Domain.Entities.SetupSessions.BootstrapImageDescriptor", "BootArtefactDescriptor", b1 =>
                        {
                            b1.Property<Guid>("SetupSessionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Init")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CmdLine");

                            b1.Property<string>("Kernel")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("KernelLocation");

                            b1.Property<string>("RamDisk")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("InitRdLocation");

                            b1.HasKey("SetupSessionId");

                            b1.ToTable("SetupSessions");

                            b1.WithOwner()
                                .HasForeignKey("SetupSessionId");
                        });

                    b.OwnsMany("PhoeNix.Domain.Entities.SetupSessions.SetupTarget", "Targets", b1 =>
                        {
                            b1.Property<Guid>("SetupSessionId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("MachineId")
                                .HasColumnType("TEXT")
                                .HasColumnName("MachineId");

                            b1.Property<string>("IpAddress")
                                .HasColumnType("TEXT")
                                .HasColumnName("IpAddress");

                            b1.Property<DateTime?>("LastErrorAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("LastErrorAtUtc");

                            b1.Property<string>("LastErrorCode")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("LastErrorCode");

                            b1.Property<string>("LastErrorDescription")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("LastErrorDescription");

                            b1.Property<string>("LastErrorSource")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("LastErrorSource");

                            b1.Property<DateTime?>("LastTransitionAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("LastTransitionAtUtc");

                            b1.Property<Guid?>("SelectedConfigurationId")
                                .HasColumnType("TEXT")
                                .HasColumnName("SelectedConfigurationId");

                            b1.Property<Guid?>("SelectedSystemId")
                                .HasColumnType("TEXT")
                                .HasColumnName("SelectedSystemId");

                            b1.Property<string>("Stage")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("SetupSessionId", "MachineId");

                            b1.HasIndex("MachineId");

                            b1.HasIndex("SelectedConfigurationId");

                            b1.HasIndex("SelectedSystemId");

                            b1.ToTable("SetupSessionTargets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SetupSessionId");

                            b1.OwnsMany("PhoeNix.Domain.Entities.SetupSessions.RankedDiskAssignment", "RankedDiskAssignments", b2 =>
                                {
                                    b2.Property<Guid>("SetupSessionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("MachineId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Index")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("RankIndex");

                                    b2.Property<string>("DiskByIdPath")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("DiskByIdPath");

                                    b2.HasKey("SetupSessionId", "MachineId", "Index");

                                    b2.HasIndex("DiskByIdPath");

                                    b2.ToTable("SetupSessionTargetRankedDisks", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SetupSessionId", "MachineId");
                                });

                            b1.OwnsOne("PhoeNix.Domain.Entities.SetupSessions.CallbackToken", "CallbackToken", b2 =>
                                {
                                    b2.Property<Guid>("SetupTargetSetupSessionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("SetupTargetMachineId")
                                        .HasColumnType("TEXT");

                                    b2.Property<DateTime>("ExpiresAtUtc")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CallbackTokenExpiresAtUtc");

                                    b2.Property<DateTime?>("RevokedAtUtc")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CallbackTokenRevokedAtUtc");

                                    b2.Property<string>("Token")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("CallbackToken");

                                    b2.HasKey("SetupTargetSetupSessionId", "SetupTargetMachineId");

                                    b2.ToTable("SetupSessionTargets");

                                    b2.WithOwner()
                                        .HasForeignKey("SetupTargetSetupSessionId", "SetupTargetMachineId");
                                });

                            b1.Navigation("CallbackToken");

                            b1.Navigation("RankedDiskAssignments");
                        });

                    b.OwnsOne("PhoeNix.Domain.Entities.SetupSessions.SshCredential", "SshCredential", b1 =>
                        {
                            b1.Property<Guid>("SetupSessionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CertificatePublicKey")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("SshCertificatePublicKey");

                            b1.Property<DateTime>("ExpiresAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("SshKeyExpiresAtUtc");

                            b1.Property<string>("PublicKey")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("SshPublicKey");

                            b1.Property<DateTime?>("RevokedAtUtc")
                                .HasColumnType("TEXT")
                                .HasColumnName("SshKeyRevokedAtUtc");

                            b1.HasKey("SetupSessionId");

                            b1.ToTable("SetupSessions");

                            b1.WithOwner()
                                .HasForeignKey("SetupSessionId");
                        });

                    b.Navigation("BootArtefactDescriptor");

                    b.Navigation("SshCredential");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.System", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", null)
                        .WithMany("SystemSpecifications")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.Configuration", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Modules");

                    b.Navigation("SystemSpecifications");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.Navigation("Followers");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleTemplate", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleValue", b =>
                {
                    b.Navigation("EditableValues");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.System", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
