// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoeNix.Persistence;

#nullable disable

namespace PhoeNix.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214155500_MoveModulesAndSystemsToConfiguration")]
    partial class MoveModulesAndSystemsToConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.FollowInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowValue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InputId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InputId");

                    b.ToTable("FollowInput");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("Inputs");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.EntryValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleValueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placeholder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT")
                        .HasColumnName("TypeDiscriminator");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleValueId");

                    b.ToTable("EntryValues");

                    b.HasDiscriminator<string>("TypeDiscriminator").HasValue("EntryValue");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModuleTemplates");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModuleTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SystemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("SystemId");

                    b.ToTable("ConfigurationModules");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleTemplateId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.System", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Architecture")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNormalUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Shell")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Uid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.MultiChoiceValue<double>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("MultiChoiceDouble");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.MultiChoiceValue<int>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("MultiChoiceInt");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.MultiChoiceValue<string>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("MultiChoiceString");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.RangeValue<double>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.Property<double>("LowerValue")
                        .HasColumnType("REAL");

                    b.Property<double>("Max")
                        .HasColumnType("REAL");

                    b.Property<double>("Min")
                        .HasColumnType("REAL");

                    b.Property<double>("UpperValue")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("RangeDouble");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.RangeValue<int>", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.Property<int>("LowerValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Min")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpperValue")
                        .HasColumnType("INTEGER");

                    b.ToTable("EntryValues", t =>
                        {
                            t.Property("LowerValue")
                                .HasColumnName("RangeValue_LowerValue");

                            t.Property("Max")
                                .HasColumnName("RangeValue_Max");

                            t.Property("Min")
                                .HasColumnName("RangeValue_Min");

                            t.Property("UpperValue")
                                .HasColumnName("RangeValue_UpperValue");
                        });

                    b.HasDiscriminator().HasValue("RangeInt");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.TextValue", b =>
                {
                    b.HasBaseType("PhoeNix.Domain.Entities.Modules.EntryValue");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.FollowInput", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Inputs.Input", null)
                        .WithMany("Followers")
                        .HasForeignKey("InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", null)
                        .WithMany("Inputs")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.EntryValue", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Modules.ModuleValue", null)
                        .WithMany("EditableValues")
                        .HasForeignKey("ModuleValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleTemplate", b =>
                {
                    b.OwnsMany("PhoeNix.Domain.Entities.Modules.EntryValueDefinition", "EditableValueTypes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<int>("InputType")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ModuleTemplateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Placeholder")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ModuleTemplateId");

                            b1.ToTable("EntryValueDefinition");

                            b1.WithOwner()
                                .HasForeignKey("ModuleTemplateId");
                        });

                    b.Navigation("EditableValueTypes");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleValue", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", null)
                        .WithMany("Modules")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhoeNix.Domain.Entities.Systems.System", null)
                        .WithMany("Modules")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.Test", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Modules.ModuleTemplate", null)
                        .WithMany("Tests")
                        .HasForeignKey("ModuleTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.System", b =>
                {
                    b.HasOne("PhoeNix.Domain.Entities.Configurations.Configuration", null)
                        .WithMany("SystemSpecifications")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Configurations.Configuration", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Modules");

                    b.Navigation("SystemSpecifications");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Inputs.Input", b =>
                {
                    b.Navigation("Followers");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleTemplate", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Modules.ModuleValue", b =>
                {
                    b.Navigation("EditableValues");
                });

            modelBuilder.Entity("PhoeNix.Domain.Entities.Systems.System", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
