<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Quartz" Version="3.13.1"/>
        <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.13.1"/>
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PhoeNix.Persistence\PhoeNix.Persistence.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Newtonsoft.Json">
            <HintPath>..\..\..\..\..\.nuget\packages\newtonsoft.json\13.0.1\lib\netstandard2.0\Newtonsoft.Json.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
