name: Nix Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Go to development environment
      shell: bash
      run: |
        nix develop
        env
        echo $PLAYWRIGHT_LAUNCH_OPTIONS_EXECUTABLE_PATH
        echo "PLAYWRIGHT_LAUNCH_OPTIONS_EXECUTABLE_PATH=${PLAYWRIGHT_LAUNCH_OPTIONS_EXECUTABLE_PATH}" >> $GITHUB_ENV

    - name: Test Nix WebAPI
      run: dotnet test sources/tests/PhoeNix.WebAPI.Tests/PhoeNix.WebAPI.Tests.csproj
    - name: Test Nix WebApp
      run: dotnet test sources/tests/PhoeNix.WebAPP.Tests/PhoeNix.WebAPP.Tests.csproj -- Playwright.LaunchOptions.ExecutablePath=${{ env.PLAYWRIGHT_LAUNCH_OPTIONS_EXECUTABLE_PATH }}
