name: Nix Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Domain Unit Tests
        run: nix develop --command dotnet test sources/tests/PhoeNix.Domain.UnitTests/PhoeNix.Domain.UnitTests.csproj

      - name: Run Application Unit Tests
        run: nix develop --command dotnet test sources/tests/PhoeNix.Application.UnitTests/PhoeNix.Application.UnitTests.csproj

      - name: Run WebAPI Tests
        run: nix develop --command dotnet test sources/tests/PhoeNix.WebAPI.Tests/PhoeNix.WebAPI.Tests.csproj

      - name: Run WebApp Playwright Tests
        run: nix develop --command bash -c "cd sources/tests/PhoeNix.WebAPP.Tests && nix run .#playwright"
