<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PhoeNix.Domain\PhoeNix.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1"/>
        <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2"/>
        <PackageReference Include="System.IO.Abstractions" Version="22.0.14"/>
        <PackageReference Include="System.Text.Json" Version="10.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Microsoft.Extensions.Options">
            <HintPath>..\..\..\..\..\..\.nuget\packages\microsoft.extensions.options\8.0.2\lib\net8.0\Microsoft.Extensions.Options.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
